# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Pf-Lhb1YLK68wWreLct9sE7-C3dZ97HY
"""

import matplotlib.pyplot as plt
import numpy as np

# Create the trajectory
h=490 #let
v=1.5 #let
H=np.array([0,h])
H=H.reshape(1,2)
V=np.array([v,0])
V=V.reshape(1,2)

g=np.array([0,-9.8])
g=g.reshape(1,2)
T = np.linspace(0,11,300)
T=T.reshape(300,1)

X=H+T*V+0.5*np.square(T)*g

plt.figure(0)
# Create the plot
plt.plot(X[:,0],X[:,1],label='motion(ground)')

# Add a title
plt.title('')

# Add X and y Label
plt.xlabel('x axis')
plt.ylabel('y axis')

# Add a grid
plt.grid(alpha=1,linestyle='--')

plt.ylim(0,500)

# Add a Legend
plt.legend()
plt.show()

#second trajectory
plt.figure(1)
vr=0
V=np.array([0,0])
V=V.reshape(1,2)

a=np.array([1,0])
ar=np.subtract(g,a)
ar.reshape(1,2)
X=T*V+0.5*np.square(T)*ar
print(X[0,1])
# Create the plot
plt.plot(X[:,0],X[:,1],label='motion(train)')

# Add a title
plt.title('')

# Add X and y Label
plt.xlabel('x axis')
plt.ylabel('y axis')

# Add a grid

plt.grid(alpha=1,linestyle='--')

plt.ylim(-500,5)

# Add a Legend
plt.legend()
plt.show()