# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZuXwva4BeHTPcq3dwf6DJ-lFmEfYzbEJ
"""

#code by Satya Sangram
#for quadforms 2.41
import numpy as np
import matplotlib.pyplot as plt

def line_dir_pt(m,A,k1,k2):
  len = 10
  dim = A.shape[0]
  x_AB = np.zeros((dim,len))
  lam_1 = np.linspace(k1,k2,len)
  for i in range(len):
    temp1 = A + lam_1[i]*m
    x_AB[:,i]= temp1.T
  return x_AB

#Plottiing curve
x=np.linspace(0,7,40)
y=-2/(x-3)
plt.plot(x,y,label='Curve')
#Input parameters
P = np.array(([4,-2]))
Q = np.array(([2,2]))
m = np.array(([1,2]))
k1 = 2
k2 = -2
##Generating all lines
x_AB = line_dir_pt(m,P,k1,k2)
x_BC = line_dir_pt(m,Q,k1,k2)
#Plotting all lines
plt.plot(x_AB[0,:],x_AB[1,:],label='$Tangent1$')
plt.plot(x_BC[0,:],x_BC[1,:],label='$Tangent2$')


plt.ylim([-8,8])
plt.xlabel('$x$')
plt.ylabel('$y$')
plt.legend(loc='lower right')
plt.grid() # minor
plt.show()